baseURL = "http://labs.oneoverzero.org/"
languageCode = "pt-pt"


description = 'OOZ Labs - Construimos, arranjamos, melhoramos, estragamos, combinamos, inventamos, alteramos... e mostramos como se faz.'

DefaultContentLanguage = "en"
#DefaultContentLanguage = "ja"
title = "One Over Zero Labs"
theme = "beautifulhugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"
pygmentsUseClasses = true
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
#pygmentsUseClassic = true
#pygmentOptions = "linenos=inline"
#disqusShortname = "XXX"
googleAnalytics = "UA-53355360-1"

[permalinks]
  post = "/:slug/"
  page = "/:section/:slug/"
  
[Params]
#  homeTitle = "Beautiful Hugo Theme" # Set a different text for the header on the home page
  subtitle = "Construimos, arranjamos, melhoramos, estragamos, combinamos, inventamos, alteramos... e mostramos como se faz."
  logo = "/static/oozlabs_squarelogo_dark.png" # Expecting square dimensions
  favicon = "img/favicon.ico"
  dateFormat = "January 2, 2006"
  commit = false
  rss = true
  comments = true
  readingTime = true
  wordCount = false
  useHLJS = true
  socialShare = true
  delayDisqus = true
  showRelatedPosts = true
#  gcse = "012345678901234567890:abcdefghijk" # Get your code from google.com/cse. Make sure to go to "Look and Feel" and change Layout to "Full Width" and Theme to "Classic"

#[[Params.bigimg]]
#  src = "img/triangle.jpg"
#  desc = "Triangle"
#[[Params.bigimg]]
#  src = "img/sphere.jpg"
#  desc = "Sphere"
#  # position: see values of CSS background-position.
#  position = "center top"
#[[Params.bigimg]]
#  src = "img/hexagon.jpg"
#  desc = "Hexagon"

[Author]
  name = "OOZ Labs"
#  website = "yourwebsite.com"
#  email = "youremail@domain.com"
  facebook = "oozlabs"
  googleplus = "108701695142339153954" # or xxxxxxxxxxxxxxxxxxxxx
  github = "OOZLabs"
#  gitlab = "username"
#  bitbucket = "username"
  twitter = "oozlabs"
#  reddit = "username"
#  linkedin = "username"
#  xing = "username"
#  stackoverflow = "users/XXXXXXX/username"
#  snapchat = "username"
  instagram = "oozlabs"
  youtube = "channel/UCyupGmfELyDSQZK7rDBpaJw" # or channel/channelname
#  soundcloud = "username"
#  spotify = "username"
#  bandcamp = "username"
#  itchio = "username"
#  vk = "username"
#  paypal = "username"
#  telegram = "username"
#  500px = "username"

[[menu.main]]
    name = "A Equipa"
    url = "/equipa/"
    weight = 10

[[menu.main]]
    name = "Contacto"
    url = "/contacto/"
    weight = 20

[[menu.main]]
    identifier = "Parcerias"
    name = "Parcerias"
    url = "/parcerias/"
    weight = 30

[[menu.main]]
    parent = ""
    name = "Projectos"
    url = "/projectos/"
    weight = 40

[[menu.main]]
    parent = "Projectos"
    name = "Convidado Especial, Baílio Vieira"
    url = "/projectos/convidado-especial-basilio-vieira/"
    weight = 50

[[menu.main]]
    parent = ""
    name = "Séries"
    url = "/series/"
    weight = 50

[[menu.main]]
    parent = ""
    name = "Séries"
    url = "/series/"
    weight = 50

[[menu.main]]
    parent = ""
    name = "Séries"
    url = "/series/"
    weight = 50

[[menu.main]]
    parent = ""
    name = "Séries"
    url = "/series/"
    weight = 50


